#!/bin/sh
#
# Starts thermostat server.
#

start() {
    printf "Starting thermostat server: "

    start-stop-daemon -S -q \
        --make-pidfile --pidfile /var/run/thermostat.pid \
        --exec /usr/sbin/logall thermostat.server /usr/sbin/server.py \
        --background
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping thermostat server: "
    start-stop-daemon -K -q --pidfile /var/run/thermostat.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
