#!/bin/sh
#
# Starts garage server.
#

start() {
    printf "Starting garage server: "

    start-stop-daemon -S -q \
        --make-pidfile --pidfile /var/run/garage.pid \
        --exec /usr/sbin/logall garage.server /usr/sbin/server.py \
        --background
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping garage server: "
    start-stop-daemon -K -q --pidfile /var/run/garage.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
